sudo: required
dist: trusty
language: c

# Pre-install missing build dependencies:
# - libcheck 0.9.10 is slightly too old, since 0.9.12 adds TAP support
install:
        - wget http://downloads.sourceforge.net/project/check/check/0.10.0/check-0.10.0.tar.gz
        - tar -xvf check-0.10.0.tar.gz
        - pushd check-0.10.0 && ./configure --prefix=/usr && make -j48 && sudo make install && popd

# Ubuntu's default umask is 0002, but this break's swupd hash calculations.
script:
        - sudo find test/functional -exec chmod g-w {} \;
        - autoreconf --verbose --warnings=none --install --force && ./configure && make -j48 && sudo sh -c 'umask 0022 && make -j48 check'
after_failure: cat test-suite.log && sudo ls -lRZ test/functional
